name: flutter_application_1
description: "A new Flutter project."

# Prevent publishing to pub.dev
publish_to: 'none'

# Version and build number
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  http: ^1.2.2
  path_provider: ^2.0.9
  velocity_x: 4.2.1
  lottie: ^3.1.2
  get: ^4.6.6
  flutter_keyboard_visibility: ^6.0.0
  animate_do: ^3.1.2
  firebase_core: ^2.24.2
  google_sign_in: ^6.2.1
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  flutter_easyloading: ^3.0.5
  firebase_messaging: ^14.7.10
  carousel_slider: ^4.2.1
  cached_network_image: ^3.4.0
  smooth_page_indicator: ^1.2.0+3
  image_card: ^0.0.4
  flutter_swipe_action_cell: ^3.1.3
  iconsax: ^0.0.8
  sticky_headers: ^0.3.0+2
  image_picker: ^1.1.2
  firebase_storage: ^11.6.0
  flutter_rating_bar: ^4.0.1
  sheet: ^1.0.0
  draggable_bottom_sheet: ^1.0.2
  uuid: ^4.4.2
  intl: ^0.19.0
  googleapis_auth: ^1.6.0
  app_settings: ^5.1.1
  flutter_local_notifications: ^17.2.2
  razorpay_flutter: ^1.3.7
  url_launcher: ^6.3.0
  mailer: ^6.1.2
  flutter_email_sender: ^6.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/
  - assets/images/signinGoogle.png
  - assets/images/signinEmail.png
 