// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjcVQALd71MnMEEE8owg7AGCv-dco3sNY',
    appId: '1:635663434875:web:80fad9ea285e6264d4cede',
    messagingSenderId: '635663434875',
    projectId: 'e-commerece-f7d89',
    authDomain: 'e-commerece-f7d89.firebaseapp.com',
    storageBucket: 'e-commerece-f7d89.appspot.com',
    measurementId: 'G-JHM1PBZ75Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8hDj3Dqztqz7s42EFjh7Q2r0qNPsrxzQ',
    appId: '1:635663434875:android:ed14551eaec98b70d4cede',
    messagingSenderId: '635663434875',
    projectId: 'e-commerece-f7d89',
    storageBucket: 'e-commerece-f7d89.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFDxmWRoPJsZXlsy7NevG4O4M1JXP1SGI',
    appId: '1:635663434875:ios:7d1bddbda9532655d4cede',
    messagingSenderId: '635663434875',
    projectId: 'e-commerece-f7d89',
    storageBucket: 'e-commerece-f7d89.appspot.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFDxmWRoPJsZXlsy7NevG4O4M1JXP1SGI',
    appId: '1:635663434875:ios:7d1bddbda9532655d4cede',
    messagingSenderId: '635663434875',
    projectId: 'e-commerece-f7d89',
    storageBucket: 'e-commerece-f7d89.appspot.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjcVQALd71MnMEEE8owg7AGCv-dco3sNY',
    appId: '1:635663434875:web:ab6f3e0c06e238d2d4cede',
    messagingSenderId: '635663434875',
    projectId: 'e-commerece-f7d89',
    authDomain: 'e-commerece-f7d89.firebaseapp.com',
    storageBucket: 'e-commerece-f7d89.appspot.com',
    measurementId: 'G-FT8NL1GGYT',
  );
}
